title: Macro Claw
description: 매크로 경제 & OpenClow 활용 가이드
author: thanksdany
lang: ko
timezone: Asia/Seoul

theme: minima

header_pages:
  - index.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - vendor/
  - vendor/bundle/
  - .github/
  - agents/
  - memory/
  - skills/
  - Gemfile
  - Gemfile.lock
  - AGENTS.md
  - BOOTSTRAP.md
  - HEARTBEAT.md
  - IDENTITY.md
  - SOUL.md
  - TOOLS.md
  - USER.md
